### ISSUE TITLE
ElectronHelloWorld: dotnet restore fails

### ISSUE THREAD

**Issue by jaredthirsk** [dsuryd/dotnetify-react-demo#2]
`
...
D:\dev\dotnetify-react-demo\ElectronHelloWorld\ElectronHelloWorld.csproj : error                            NU1202: Package DotNetify.SignalR 3.0.0-pre is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package DotNetify.SignalR 3.0.0-pre supports: netstandard2.0 (.NETStandard,Version=v2.0)
...
`

**Comment by dsuryd** [comment]
Thank's, this is now fixed.
